In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

BASE_DIR = Path(r"C:\Users\Luciano Sotelo\Documents\TESIS_PODER_JUDICIAL")

RUTA_ORIGINAL = BASE_DIR / "01_datos_originales" / "base_poder_judicial_original_2022_2024.xlsx"
RUTA_LIMPIA = BASE_DIR / "02_datos_limpios" / "base_poder_judicial_limpia_v1.xlsx"

print(RUTA_ORIGINAL.exists())

True

In [4]:
df = pd.read_excel(RUTA_ORIGINAL, sheet_name="2022-2023-2024")

print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])

df.head()

Cantidad de filas: 9695
Cantidad de columnas: 54

,Fecha Intervención,sexo denunciante,Edad denunciante,Relación denunciante/denunciada,Capacidades Diferentes denunciante,Pertenencia a Pueblos Originarios denunciante,Violencia Física,Violencia Psicológica,Violencia Económica,Violencia Sexual,...,Orden para retirar enseres personales,Otras Medidas,Prohibición de acercamiento o comunicación del agresor,Recursos de Revocatoria,Reintegro al hogar a las vï¿½cticas,Restitución de alimentos,Restitución de bienes,Retiro de la víctima,Secuestro de arma,Tratamientos de rehabilitación
0,2022-03-21,F,26,7.0,2.0,2.0,0,3,0,0,...,0,1,1,0,0,0,0,0,0,0
1,2022-04-01,F,11,5.0,1.0,2.0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2022-04-29,F,23,2.0,2.0,2.0,3,2,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2022-04-07,F,21,1.0,1.0,2.0,2,3,3,0,...,0,0,1,0,0,0,0,0,0,1
4,2022-01-04,F,27,1.0,2.0,2.0,2,3,2,0,...,0,0,1,0,0,0,0,0,0,1

In [5]:
for i, col in enumerate(df.columns, start=1):
    print(i, col)

1 Fecha Intervención
2 sexo denunciante
3 Edad denunciante
4 Relación denunciante/denunciada
5 Capacidades Diferentes denunciante
6 Pertenencia a Pueblos Originarios denunciante
7 Violencia Física
8 Violencia Psicológica
9 Violencia Económica
10 Violencia Sexual
11 Violencia Restricción Participación Social
12 Violencia Ambiental
13 Frecuencia de Episodios
14 Nivel Educativo denunciante
15 Cobertura de Salud denunciante
16 Condición Laboral denunciante
17 Categoría Ocupacional
18 Tipo Domicilio denunciante
19 Procedencia de Migración denunciante
20 Cantidad de Hijos
21 Intervenciones - Justicia Penal
22 Intervenciones - Justicia Civil
23 Intervenciones - Judicial Otra
24 Intervenciones - Otras Inst. estatales
25 Intervenciones -Instit. No Gubernamentales
26 Sexo denunciada
27 Edad denunciada
28 Nivel Educativo denunciada
29 Condición Laboral denunciada
30 Barrio hecho
31 Localidad Hecho
32 Departamento Hecho
33 Origen
34 Abstención de publicación en Redes Sociales
35 Alojamiento temporario de la víctima
36 Custodia policial
37 Desestimación de denuncia
38 Exclusión del agresor
39 Fijacion de cuota alimentaria provisoria
40 Fijacion de regimen de visitas
41 Guarda de menores/incapaces
42 Guarda de menores/incpaces víctimas
43 Levantamiento de la medida judicial
44 Oficio de protección policial
45 Orden para retirar enseres personales
46 Otras Medidas
47 Prohibición de acercamiento o comunicación del agresor
48 Recursos de Revocatoria
49 Reintegro al hogar a las vï¿½cticas
50 Restitución de alimentos
51 Restitución de bienes
52 Retiro de la víctima
53 Secuestro de arma
54 Tratamientos de rehabilitación

In [6]:
resumen = pd.DataFrame({
    "columna": df.columns,
    "tipo_dato": df.dtypes.astype(str).values,
    "valores_nulos": df.isna().sum().values,
    "porcentaje_nulos": (df.isna().mean() * 100).round(2).values,
    "valores_unicos": df.nunique(dropna=True).values
})

resumen.sort_values("porcentaje_nulos", ascending=False).head(20)

,columna,tipo_dato,valores_nulos,porcentaje_nulos,valores_unicos
18,Procedencia de Migración denunciante,float64,9323,96.16,3
24,Intervenciones -Instit. No Gubernamentales,object,5352,55.20,2
22,Intervenciones - Judicial Otra,object,4954,51.10,2
23,Intervenciones - Otras Inst. estatales,object,4310,44.46,2
21,Intervenciones - Justicia Civil,object,4087,42.16,2
27,Nivel Educativo denunciada,float64,3495,36.05,10
20,Intervenciones - Justicia Penal,object,3216,33.17,2
16,Categoría Ocupacional,float64,2202,22.71,8
12,Frecuencia de Episodios,float64,2001,20.64,6
28,Condición Laboral denunciada,float64,1977,20.39,6
14,Cobertura de Salud denunciante,float64,1644,16.96,3
13,Nivel Educativo denunciante,float64,1593,16.43,11
15,Condición Laboral denunciante,float64,1378,14.21,6
17,Tipo Domicilio denunciante,float64,1292,13.33,2
5,Pertenencia a Pueblos Originarios denunciante,float64,1226,12.65,2
4,Capacidades Diferentes denunciante,float64,1191,12.28,2
3,Relación denunciante/denunciada,float64,283,2.92,8
30,Localidad Hecho,object,9,0.09,122
32,Origen,object,3,0.03,23
31,Departamento Hecho,object,1,0.01,12

In [7]:
duplicados = df.duplicated().sum()
print("Filas duplicadas exactas:", duplicados)

Filas duplicadas exactas: 6

In [8]:
df_limpia = df.copy()

df_limpia.columns = (
    df_limpia.columns
    .str.strip()
    .str.replace("  ", " ", regex=False)
)

df_limpia = df_limpia.rename(columns={
    "sexo denunciante": "Sexo denunciante",
    "Fijacion de cuota alimentaria provisoria": "Fijación de cuota alimentaria provisoria",
    "Fijacion de regimen de visitas": "Fijación de régimen de visitas",
    "Guarda de menores/incpaces víctimas": "Guarda de menores/incapaces víctimas",
    "Reintegro al hogar a las vï¿½cticas": "Reintegro al hogar a las víctimas",
    "Intervenciones -Instit. No Gubernamentales": "Intervenciones - Instit. No Gubernamentales"
})

df_limpia.columns.tolist()

['Fecha Intervención',
 'Sexo denunciante',
 'Edad denunciante',
 'Relación denunciante/denunciada',
 'Capacidades Diferentes denunciante',
 'Pertenencia a Pueblos Originarios denunciante',
 'Violencia Física',
 'Violencia Psicológica',
 'Violencia Económica',
 'Violencia Sexual',
 'Violencia Restricción Participación Social',
 'Violencia Ambiental',
 'Frecuencia de Episodios',
 'Nivel Educativo denunciante',
 'Cobertura de Salud denunciante',
 'Condición Laboral denunciante',
 'Categoría Ocupacional',
 'Tipo Domicilio denunciante',
 'Procedencia de Migración denunciante',
 'Cantidad de Hijos',
 'Intervenciones - Justicia Penal',
 'Intervenciones - Justicia Civil',
 'Intervenciones - Judicial Otra',
 'Intervenciones - Otras Inst. estatales',
 'Intervenciones - Instit. No Gubernamentales',
 'Sexo denunciada',
 'Edad denunciada',
 'Nivel Educativo denunciada',
 'Condición Laboral denunciada',
 'Barrio hecho',
 'Localidad Hecho',
 'Departamento Hecho',
 'Origen',
 'Abstención de publicación en Redes Sociales',
 'Alojamiento temporario de la víctima',
 'Custodia policial',
 'Desestimación de denuncia',
 'Exclusión del agresor',
 'Fijación de cuota alimentaria provisoria',
 'Fijación de régimen de visitas',
 'Guarda de menores/incapaces',
 'Guarda de menores/incapaces víctimas',
 'Levantamiento de la medida judicial',
 'Oficio de protección policial',
 'Orden para retirar enseres personales',
 'Otras Medidas',
 'Prohibición de acercamiento o comunicación del agresor',
 'Recursos de Revocatoria',
 'Reintegro al hogar a las víctimas',
 'Restitución de alimentos',
 'Restitución de bienes',
 'Retiro de la víctima',
 'Secuestro de arma',
 'Tratamientos de rehabilitación']

In [9]:
def corregir_texto_mojibake(valor):
    if pd.isna(valor):
        return valor
    
    if not isinstance(valor, str):
        return valor
    
    texto = valor.strip()
    
    try:
        texto_corregido = texto.encode("latin1").decode("utf-8")
        return texto_corregido
    except:
        return texto

columnas_texto = [
    "Barrio hecho",
    "Localidad Hecho",
    "Departamento Hecho",
    "Origen"
]

for col in columnas_texto:
    if col in df_limpia.columns:
        df_limpia[col] = df_limpia[col].apply(corregir_texto_mojibake)

df_limpia[columnas_texto].head()

,Barrio hecho,Localidad Hecho,Departamento Hecho,Origen
0,Sin Especificar,Banco Payagua,Laishi,Juzgado de Paz - Herradura
1,Sin Especificar,Bartolomé de Las Casas,Patiño,UAVT
2,Bartolomé de Las Casas,Bartolomé de Las Casas,Patiño,UAVT
3,Bartolomé de Las Casas,Bartolomé de Las Casas,Patiño,Cdte. Fontana - Juzgado de Paz
4,Bartolomé de Las Casas,Bartolomé de Las Casas,Patiño,Cdte. Fontana - Juzgado de Paz

In [10]:
df_limpia["Fecha Intervención"] = pd.to_datetime(
    df_limpia["Fecha Intervención"],
    errors="coerce",
    dayfirst=True
)

df_limpia["Año"] = df_limpia["Fecha Intervención"].dt.year
df_limpia["Mes"] = df_limpia["Fecha Intervención"].dt.month

df_limpia[["Fecha Intervención", "Año", "Mes"]].head()

  Fecha Intervención   Año  Mes
0         2022-03-21  2022    3
1         2022-04-01  2022    4
2         2022-04-29  2022    4
3         2022-04-07  2022    4
4         2022-01-04  2022    1

In [11]:
casos_por_anio = df_limpia["Año"].value_counts().sort_index()
casos_por_anio

Año
2022    3213
2023    3223
2024    3259
Name: count, dtype: int64

In [12]:
df_limpia["Edad denunciante limpia"] = pd.to_numeric(
    df_limpia["Edad denunciante"],
    errors="coerce"
)

df_limpia["Edad denunciada limpia"] = pd.to_numeric(
    df_limpia["Edad denunciada"],
    errors="coerce"
)

df_limpia.loc[
    (df_limpia["Edad denunciante limpia"] < 1) | 
    (df_limpia["Edad denunciante limpia"] > 100),
    "Edad denunciante limpia"
] = np.nan

df_limpia.loc[
    (df_limpia["Edad denunciada limpia"] < 1) | 
    (df_limpia["Edad denunciada limpia"] > 100),
    "Edad denunciada limpia"
] = np.nan

df_limpia[["Edad denunciante", "Edad denunciante limpia", "Edad denunciada", "Edad denunciada limpia"]].describe()

,Edad denunciante,Edad denunciante limpia,Edad denunciada,Edad denunciada limpia
count,9695.000000,9205.000000,9.695000e+03,8686.000000
mean,35.332439,36.641173,4.443307e+03,36.621690
std,47.670714,14.001318,4.342511e+05,12.327319
min,0.000000,3.000000,0.000000e+00,1.000000
25%,25.000000,26.000000,2.400000e+01,27.000000
50%,33.000000,34.000000,3.300000e+01,35.000000
75%,43.000000,44.000000,4.300000e+01,44.000000
max,4425.000000,94.000000,4.275778e+07,96.000000

In [13]:
variables_violencia = [
    "Violencia Física",
    "Violencia Psicológica",
    "Violencia Económica",
    "Violencia Sexual",
    "Violencia Restricción Participación Social",
    "Violencia Ambiental"
]

for col in variables_violencia:
    df_limpia[col] = pd.to_numeric(df_limpia[col], errors="coerce")
    df_limpia[col + " constatada"] = np.where(df_limpia[col] > 0, 1, 0)

df_limpia[[col + " constatada" for col in variables_violencia]].head()

,Violencia Física constatada,Violencia Psicológica constatada,Violencia Económica constatada,Violencia Sexual constatada,Violencia Restricción Participación Social constatada,Violencia Ambiental constatada
0,0,1,0,0,0,1
1,0,0,0,1,0,0
2,1,1,0,0,0,1
3,1,1,1,0,1,1
4,1,1,1,0,1,1

In [14]:
resumen_violencias = []

for col in variables_violencia:
    casos = df_limpia[col + " constatada"].sum()
    porcentaje = casos / len(df_limpia) * 100
    
    resumen_violencias.append({
        "Tipo de violencia": col,
        "Casos": int(casos),
        "Porcentaje": round(porcentaje, 2)
    })

resumen_violencias = pd.DataFrame(resumen_violencias)
resumen_violencias.sort_values("Casos", ascending=False)

                            Tipo de violencia  Casos  Porcentaje
1                       Violencia Psicológica   6957       71.76
0                            Violencia Física   3428       35.36
5                         Violencia Ambiental   2520       25.99
2                         Violencia Económica   2038       21.02
4  Violencia Restricción Participación Social   1633       16.84
3                            Violencia Sexual    599        6.18

In [15]:
medidas_judiciales = [
    "Abstención de publicación en Redes Sociales",
    "Alojamiento temporario de la víctima",
    "Custodia policial",
    "Desestimación de denuncia",
    "Exclusión del agresor",
    "Fijación de cuota alimentaria provisoria",
    "Fijación de régimen de visitas",
    "Guarda de menores/incapaces",
    "Guarda de menores/incapaces víctimas",
    "Levantamiento de la medida judicial",
    "Oficio de protección policial",
    "Orden para retirar enseres personales",
    "Otras Medidas",
    "Prohibición de acercamiento o comunicación del agresor",
    "Recursos de Revocatoria",
    "Reintegro al hogar a las víctimas",
    "Restitución de alimentos",
    "Restitución de bienes",
    "Retiro de la víctima",
    "Secuestro de arma",
    "Tratamientos de rehabilitación"
]

resumen_medidas = []

for col in medidas_judiciales:
    if col in df_limpia.columns:
        df_limpia[col] = pd.to_numeric(df_limpia[col], errors="coerce").fillna(0)
        casos = df_limpia[col].sum()
        porcentaje = casos / len(df_limpia) * 100
        
        resumen_medidas.append({
            "Medida judicial": col,
            "Casos": int(casos),
            "Porcentaje": round(porcentaje, 2)
        })

resumen_medidas = pd.DataFrame(resumen_medidas)
resumen_medidas.sort_values("Casos", ascending=False).head(10)

                                      Medida judicial  Casos  Porcentaje
13  Prohibición de acercamiento o comunicación del...   5355       55.23
20                     Tratamientos de rehabilitación   2392       24.67
12                                      Otras Medidas   2255       23.26
10                      Oficio de protección policial   1660       17.12
4                               Exclusión del agresor   1436       14.81
0         Abstención de publicación en Redes Sociales   1272       13.12
3                           Desestimación de denuncia   1005       10.37
5            Fijación de cuota alimentaria provisoria    117        1.21
15                  Reintegro al hogar a las víctimas     95        0.98
11              Orden para retirar enseres personales     62        0.64

In [16]:
df_limpia.to_excel(RUTA_LIMPIA, index=False)

print("Base limpia guardada en:")
print(RUTA_LIMPIA)

Base limpia guardada en:
C:\Users\Luciano Sotelo\Documents\TESIS_PODER_JUDICIAL\02_datos_limpios\base_poder_judicial_limpia_v1.xlsx